"""handle function deletion in related tables

Revision ID: 02c0be279ee6
Revises: 9ab977d239eb
Create Date: 2025-06-05 12:44:39.592569

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02c0be279ee6"
down_revision: Union[str, None] = "9ab977d239eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "gardens_modal_functions_modal_function_id_fkey",
        "gardens_modal_functions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "gardens_modal_functions",
        "modal_functions",
        ["modal_function_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gardens_modal_functions", type_="foreignkey")
    op.create_foreign_key(
        "gardens_modal_functions_modal_function_id_fkey",
        "gardens_modal_functions",
        "modal_functions",
        ["modal_function_id"],
        ["id"],
    )
    # ### end Alembic commands ###
