"""do not duplicate owner information from modal app onto functions

Revision ID: 07a32efd0e27
Revises: a2fd55e29f23
Create Date: 2024-09-30 23:24:55.103750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a32efd0e27'
down_revision: Union[str, None] = 'a2fd55e29f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modal_functions_user_id_fkey', 'modal_functions', type_='foreignkey')
    op.drop_column('modal_functions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_functions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('modal_functions_user_id_fkey', 'modal_functions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
