"""missing fields on related metadata

Revision ID: 0bf4afea3e94
Revises: 949a58077872
Create Date: 2024-06-05 23:59:10.649968

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0bf4afea3e94"
down_revision: Union[str, None] = "949a58077872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset_metadata", sa.Column("title", sa.String(), nullable=False))
    op.drop_constraint("dataset_metadata_doi_key", "dataset_metadata", type_="unique")
    op.add_column("paper_metadata", sa.Column("title", sa.String(), nullable=False))
    op.add_column(
        "paper_metadata",
        sa.Column("authors", postgresql.ARRAY(sa.String()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_metadata", "authors")
    op.drop_column("paper_metadata", "title")
    op.create_unique_constraint("dataset_metadata_doi_key", "dataset_metadata", ["doi"])
    op.drop_column("dataset_metadata", "title")
    # ### end Alembic commands ###
