"""updated modal apps for async flow

Revision ID: 105d7a362d93
Revises: a932fe24661c
Create Date: 2024-11-21 16:19:22.320295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "105d7a362d93"
down_revision: Union[str, None] = "a932fe24661c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    async_modal_job_status = postgresql.ENUM(
        "PENDING", "ERROR", "DONE", "TIMED_OUT", name="asyncmodaljobstatus"
    )
    invocation_status = postgresql.ENUM(
        "PENDING", "ERROR", "DONE", "TIMED_OUT", name="invocationstatus"
    )
    invocation_status.create(op.get_bind())
    async_modal_job_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_apps",
        sa.Column(
            "deploy_status",
            sa.Enum(
                "PENDING", "DONE", "ERROR", "TIMED_OUT", name="asyncmodaljobstatus"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "modal_apps",
        sa.Column(
            "deploy_error",
            sa.String(),
            nullable=True,
        ),
    )
    op.execute("ALTER TABLE modal_invocations ALTER COLUMN status TYPE TEXT")
    op.execute(
        "ALTER TABLE modal_invocations ALTER COLUMN status TYPE asyncmodaljobstatus USING status::asyncmodaljobstatus"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TABLE modal_invocations ALTER COLUMN status TYPE TEXT")
    op.execute(
        "ALTER TABLE modal_invocations ALTER COLUMN status TYPE invocationstatus USING status::invocationstatus"
    )
    op.drop_column("modal_apps", "deploy_status")
    op.drop_column("modal_apps", "deploy_error")
    # ### end Alembic commands ###
