"""Add FailedSearchIndexSync

Revision ID: 13a336b678b0
Revises: f293268b31c5
Create Date: 2024-07-22 19:31:22.166931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13a336b678b0"
down_revision: Union[str, None] = "f293268b31c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_search_index_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("operation_type", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("failed_search_index_updates")
    # ### end Alembic commands ###
