"""remove is_test from gardens

Revision ID: 1db34d77bcf0
Revises: 68ef739dc635
Create Date: 2025-04-25 12:54:50.415294

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1db34d77bcf0"
down_revision: Union[str, None] = "68ef739dc635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gardens", "is_test")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gardens",
        sa.Column(
            "is_test",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )

    # Populate is_test with doi_is_draft values
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE gardens SET is_test = doi_is_draft"))
    # ### end Alembic commands ###
