"""add gardens table and gardens_entrypoints association

Revision ID: 21e1daef4f84
Revises: 0bf4afea3e94
Create Date: 2024-06-10 00:15:56.349551

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21e1daef4f84"
down_revision: Union[str, None] = "0bf4afea3e94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gardens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("doi", sa.String(), nullable=False),
        sa.Column("doi_is_draft", sa.Boolean(), nullable=False),
        sa.Column("authors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("contributors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=False),
        sa.Column("year", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_table(
        "gardens_entrypoints",
        sa.Column("garden_doi", sa.String(), nullable=False),
        sa.Column("entrypoint_doi", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entrypoint_doi"],
            ["entrypoints.doi"],
        ),
        sa.ForeignKeyConstraint(
            ["garden_doi"],
            ["gardens.doi"],
        ),
        sa.PrimaryKeyConstraint("garden_doi", "entrypoint_doi"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gardens_entrypoints")
    op.drop_table("gardens")
    # ### end Alembic commands ###
