"""add deployment output to modal apps

Revision ID: 265af160978d
Revises: 68ef739dc635
Create Date: 2025-04-24 17:41:23.410620

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "265af160978d"
down_revision: Union[str, None] = "68ef739dc635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_apps", sa.Column("deployment_output", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_apps", "deployment_output")
    # ### end Alembic commands ###
