"""remove hpc deployments

Revision ID: 2700137da902
Revises: 61ea68115e5a
Create Date: 2025-10-27 21:33:55.163945

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2700137da902"
down_revision: Union[str, None] = "61ea68115e5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hpc_functions_hpc_endpoints",
        sa.Column("hpc_function_id", sa.Integer(), nullable=False),
        sa.Column("hpc_endpoint_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hpc_endpoint_id"],
            ["hpc_endpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hpc_function_id"],
            ["hpc_functions.id"],
        ),
        sa.PrimaryKeyConstraint("hpc_function_id", "hpc_endpoint_id"),
    )
    op.drop_table("hpc_functions_hpc_deployments")
    op.drop_table("hpc_deployment_endpoints")
    op.drop_table("hpc_deployments")
    op.alter_column(
        "hpc_endpoints", "gcmu_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "hpc_invocation_logs", "function_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "hpc_invocation_logs",
        "hpc_endpoint_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hpc_invocation_logs",
        "hpc_endpoint_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "hpc_invocation_logs", "function_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "hpc_endpoints", "gcmu_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_table(
        "hpc_deployment_endpoints",
        sa.Column(
            "hpc_deployment_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("hpc_endpoint_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["hpc_deployment_id"],
            ["hpc_deployments.id"],
            name=op.f("hpc_deployment_endpoints_hpc_deployment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["hpc_endpoint_id"],
            ["hpc_endpoints.id"],
            name=op.f("hpc_deployment_endpoints_hpc_endpoint_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "hpc_deployment_id",
            "hpc_endpoint_id",
            name=op.f("hpc_deployment_endpoints_pkey"),
        ),
    )
    op.create_table(
        "hpc_deployments",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('hpc_deployments_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("conda_env_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "user_endpoint_config",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="hpc_deployments_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "hpc_functions_hpc_deployments",
        sa.Column("hpc_function_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "hpc_deployment_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["hpc_deployment_id"],
            ["hpc_deployments.id"],
            name=op.f("hpc_functions_hpc_deployments_hpc_deployment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["hpc_function_id"],
            ["hpc_functions.id"],
            name=op.f("hpc_functions_hpc_deployments_hpc_function_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "hpc_function_id",
            "hpc_deployment_id",
            name=op.f("hpc_functions_hpc_deployments_pkey"),
        ),
    )
    op.drop_table("hpc_functions_hpc_endpoints")
    # ### end Alembic commands ###
