"""add is_test bool to gardens

Revision ID: 2db506315e76
Revises: 439848cfb104
Create Date: 2024-12-11 19:38:28.567051

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from src.models import Garden

# revision identifiers, used by Alembic.
revision: str = "2db506315e76"
down_revision: Union[str, None] = "439848cfb104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "gardens",
        sa.Column("is_test", sa.Boolean(), nullable=False, server_default="false"),
    )

    # Init is_test to have the same value as doi_is_draft
    connection = op.get_bind()
    connection.execute(
        Garden.__table__.update().values(is_test=Garden.__table__.c.doi_is_draft)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gardens", "is_test")
    # ### end Alembic commands ###
