"""try adding a modal_app_id field to ModalFunction model

Revision ID: 2f4ff0f6c36e
Revises: 45e790abe515
Create Date: 2024-10-02 21:38:34.894550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4ff0f6c36e'
down_revision: Union[str, None] = '45e790abe515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_functions', sa.Column('modal_app_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'modal_functions', 'modal_apps', ['modal_app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modal_functions', type_='foreignkey')
    op.drop_column('modal_functions', 'modal_app_id')
    # ### end Alembic commands ###
