"""failed search index updates

Revision ID: 3a7478813c63
Revises: 9e729cff276d
Create Date: 2024-08-01 14:57:56.152875

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3a7478813c63"
down_revision: Union[str, None] = "9e729cff276d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_search_index_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(), nullable=False),
        sa.Column("operation_type", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("failed_search_index_updates")
    # ### end Alembic commands ###
