"""Link Gardens to modal_functions

Revision ID: 40c327013756
Revises: ed639e44d5f1
Create Date: 2024-09-05 20:18:58.533473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c327013756'
down_revision: Union[str, None] = 'ed639e44d5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gardens_modal_functions',
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('modal_function_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['modal_function_id'], ['modal_functions.id'], ),
    sa.PrimaryKeyConstraint('garden_id', 'modal_function_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gardens_modal_functions')
    # ### end Alembic commands ###
