"""update models

Revision ID: 439848cfb104
Revises: 105d7a362d93
Create Date: 2024-12-02 22:05:19.403578

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "439848cfb104"
down_revision: Union[str, None] = "105d7a362d93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE modal_apps SET deploy_status = 'DONE' WHERE deploy_status IS NULL"
    )

    op.add_column(
        "modal_apps",
        sa.Column("conda_requirements", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.alter_column(
        "modal_apps",
        "deploy_status",
        existing_type=postgresql.ENUM(
            "PENDING", "ERROR", "DONE", "TIMED_OUT", name="asyncmodaljobstatus"
        ),
        nullable=False,
    )
    op.add_column(
        "modal_functions",
        sa.Column("requirements", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "modal_functions",
        sa.Column("conda_requirements", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.alter_column(
        "modal_functions",
        "hardware_spec",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "modal_invocations",
        "function_call_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "modal_invocations",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "ERROR", "DONE", "TIMED_OUT", name="asyncmodaljobstatus"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modal_invocations",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "ERROR", "DONE", "TIMED_OUT", name="asyncmodaljobstatus"
        ),
        nullable=True,
    )
    op.alter_column(
        "modal_invocations",
        "function_call_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "modal_functions",
        "hardware_spec",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("modal_functions", "conda_requirements")
    op.drop_column("modal_functions", "requirements")
    op.alter_column(
        "modal_apps",
        "deploy_status",
        existing_type=postgresql.ENUM(
            "PENDING", "ERROR", "DONE", "TIMED_OUT", name="asyncmodaljobstatus"
        ),
        nullable=True,
    )
    op.drop_column("modal_apps", "conda_requirements")
    # ### end Alembic commands ###
