"""add additional fields to modal app model

Revision ID: 45e790abe515
Revises: 07a32efd0e27
Create Date: 2024-10-02 20:02:22.919368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45e790abe515'
down_revision: Union[str, None] = '07a32efd0e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_apps', sa.Column('base_image_name', sa.String(), nullable=False))
    op.add_column('modal_apps', sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modal_apps', 'requirements')
    op.drop_column('modal_apps', 'base_image_name')
    # ### end Alembic commands ###
