"""Modal functions have function names, not short names

Revision ID: 4a66b5ba6cdd
Revises: 76548c7e420c
Create Date: 2024-09-30 21:26:17.181096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a66b5ba6cdd'
down_revision: Union[str, None] = '76548c7e420c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_functions', sa.Column('function_name', sa.String(), nullable=False))
    op.drop_column('modal_functions', 'short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_functions', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('modal_functions', 'function_name')
    # ### end Alembic commands ###
