"""add entrypoint_aliases json column

Revision ID: 4b5beed10eae
Revises: 21e1daef4f84
Create Date: 2024-06-10 19:05:54.705944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b5beed10eae"
down_revision: Union[str, None] = "21e1daef4f84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gardens",
        sa.Column(
            "entrypoint_aliases", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gardens", "entrypoint_aliases")
    # ### end Alembic commands ###
