"""add notebooks field to modal functions

Revision ID: 4d528e79513e
Revises: d999772cdd94
Create Date: 2025-03-11 17:28:39.181735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d528e79513e"
down_revision: Union[str, None] = "d999772cdd94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_functions",
        sa.Column(
            "notebooks",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_functions", "notebooks")
    # ### end Alembic commands ###
