"""add deployment ownership and set null on invocations

Revision ID: 61ea68115e5a
Revises: adc39d998ba3
Create Date: 2025-10-17 17:29:26.988604

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61ea68115e5a"
down_revision: Union[str, None] = "adc39d998ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("hpc_invocation_logs_function_id_fkey"),
        "hpc_invocation_logs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("hpc_invocation_logs_hpc_endpoint_id_fkey"),
        "hpc_invocation_logs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "hpc_invocation_logs",
        "hpc_functions",
        ["function_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "hpc_invocation_logs",
        "hpc_endpoints",
        ["hpc_endpoint_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hpc_invocation_logs", type_="foreignkey")
    op.drop_constraint(None, "hpc_invocation_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("hpc_invocation_logs_hpc_endpoint_id_fkey"),
        "hpc_invocation_logs",
        "hpc_endpoints",
        ["hpc_endpoint_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("hpc_invocation_logs_function_id_fkey"),
        "hpc_invocation_logs",
        "hpc_functions",
        ["function_id"],
        ["id"],
    )
    # ### end Alembic commands ###
