"""add suggested fix to modal apps

Revision ID: 68ef739dc635
Revises: d5ae091961f1
Create Date: 2025-04-23 16:22:48.946527

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68ef739dc635"
down_revision: Union[str, None] = "d5ae091961f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("modal_apps", sa.Column("suggested_fix", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_apps", "suggested_fix")
    # ### end Alembic commands ###
