"""Tweak Modal model fields

Revision ID: 76548c7e420c
Revises: 40c327013756
Create Date: 2024-09-30 21:20:11.458489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76548c7e420c'
down_revision: Union[str, None] = '40c327013756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_apps', sa.Column('file_contents', sa.String(), nullable=False))
    op.drop_column('modal_apps', 'file_text')
    op.add_column('modal_functions', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modal_functions', 'title')
    op.add_column('modal_apps', sa.Column('file_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('modal_apps', 'file_contents')
    # ### end Alembic commands ###
