"""create pending mdf flows table

Revision ID: 79072b7ef5d4
Revises: 270b5e065306
Create Date: 2024-08-09 17:57:28.484072

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79072b7ef5d4"
down_revision: Union[str, None] = "270b5e065306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_mdf_flows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flow_action_id", sa.Uuid(), nullable=False),
        sa.Column("versioned_source_id", sa.String(), nullable=False),
        sa.Column("owner_identity_id", sa.Uuid(), nullable=False),
        sa.Column("previous_versions", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_action_id"),
        sa.UniqueConstraint("versioned_source_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_mdf_flows")
    # ### end Alembic commands ###
