"""add function_call_id to modal_invocations

Revision ID: 7e91f264a044
Revises: 7fcd1f0f86cc
Create Date: 2024-10-21 18:23:59.008100

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e91f264a044"
down_revision: Union[str, None] = "7fcd1f0f86cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_invocations", sa.Column("function_call_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_invocations", "function_call_id")
    # ### end Alembic commands ###
