"""add hardware spec to modal functions

Revision ID: 7fcd1f0f86cc
Revises: c833519fb002
Create Date: 2024-10-18 12:09:33.945728

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fcd1f0f86cc"
down_revision: Union[str, None] = "c833519fb002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_functions",
        sa.Column(
            "hardware_spec", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "modal_invocations", sa.Column("function_call_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_invocations", "function_call_id")
    op.drop_column("modal_functions", "hardware_spec")
    # ### end Alembic commands ###
