"""add modal_app_id field

Revision ID: 892bac5ccc7c
Revises: bed2401f656e
Create Date: 2025-04-10 20:01:08.526117

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "892bac5ccc7c"
down_revision: Union[str, None] = "bed2401f656e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("modal_apps", sa.Column("modal_app_id", sa.String(), nullable=True))

    # old apps can just have '' as their original name
    op.execute(
        sa.sql.text(
            "UPDATE modal_apps SET original_app_name = '' WHERE original_app_name IS NULL"
        )
    )
    op.alter_column(
        "modal_apps", "original_app_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "modal_apps", "original_app_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("modal_apps", "modal_app_id")
    # ### end Alembic commands ###
