"""Autoincrement Modal model ids

Revision ID: 90d3af5c19d3
Revises: 4a66b5ba6cdd
Create Date: 2024-09-30 21:46:27.061558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d3af5c19d3'
down_revision: Union[str, None] = '4a66b5ba6cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
