"""missing contributors column

Revision ID: 949a58077872
Revises: 9b07d1d75ae8
Create Date: 2024-06-04 17:20:18.674603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '949a58077872'
down_revision: Union[str, None] = '9b07d1d75ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_metadata', sa.Column('contributors', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_metadata', 'contributors')
    # ### end Alembic commands ###
