"""add is_archived fields

Revision ID: 949c997a709c
Revises: 92f6722af9e5
Create Date: 2024-07-26 13:10:07.660365

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "949c997a709c"
down_revision: Union[str, None] = "92f6722af9e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entrypoints", sa.Column("is_archived", sa.Boolean(), nullable=True))
    op.add_column("gardens", sa.Column("is_archived", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gardens", "is_archived")
    op.drop_column("entrypoints", "is_archived")
    # ### end Alembic commands ###
