"""handle function deletion in related tables

Revision ID: 94dfc9916805
Revises: 9ab977d239eb
Create Date: 2025-06-06 13:20:37.993745

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94dfc9916805"
down_revision: Union[str, None] = "9ab977d239eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "benchmark_runs", "task_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "benchmark_runs", "function_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "benchmark_runs", "invocation_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "gardens_modal_functions_modal_function_id_fkey",
        "gardens_modal_functions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "gardens_modal_functions",
        "modal_functions",
        ["modal_function_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "benchmark_runs", "invocation_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "benchmark_runs", "function_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "benchmark_runs", "task_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
