"""cascade garden deletion to users_saved_gardens

Revision ID: 9ab977d239eb
Revises: 852df3ad8ad8
Create Date: 2025-05-16 18:31:53.684526

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ab977d239eb"
down_revision: Union[str, None] = "852df3ad8ad8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "users_saved_gardens_garden_id_fkey", "users_saved_gardens", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "users_saved_gardens",
        "gardens",
        ["garden_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_saved_gardens", type_="foreignkey")
    op.create_foreign_key(
        "users_saved_gardens_garden_id_fkey",
        "users_saved_gardens",
        "gardens",
        ["garden_id"],
        ["id"],
    )
    # ### end Alembic commands ###
