"""remove publisher field from function

Revision ID: a14f42140317
Revises: 7313b5d89c08
Create Date: 2024-09-30 23:12:39.007895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14f42140317'
down_revision: Union[str, None] = '7313b5d89c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modal_functions', 'language')
    op.drop_column('modal_functions', 'version')
    op.drop_column('modal_functions', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_functions', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
