"""add version field to modal_apps

Revision ID: a20517924976
Revises: 2db506315e76
Create Date: 2024-12-16 19:16:05.269338

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a20517924976"
down_revision: Union[str, None] = "2db506315e76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE SEQUENCE version_sequence START 1"))
    op.add_column(
        "modal_apps",
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("nextval('version_sequence')"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_apps", "version")
    op.execute(sa.text("DROP SEQUENCE version_sequence"))
    # ### end Alembic commands ###
