"""updated modal invocations for async usage

Revision ID: a932fe24661c
Revises: 7fcd1f0f86cc
Create Date: 2024-11-04 22:19:53.158785

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a932fe24661c"
down_revision: Union[str, None] = "7fcd1f0f86cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    invocation_status = postgresql.ENUM(
        "PENDING", "ERROR", "DONE", "TIMED_OUT", name="invocationstatus"
    )
    invocation_status.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_invocations", sa.Column("date_resolved", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "modal_invocations",
        sa.Column(
            "status",
            sa.Enum("PENDING", "ERROR", "DONE", "TIMED_OUT", name="invocationstatus"),
            nullable=True,
        ),
    )
    op.add_column("modal_invocations", sa.Column("error", sa.String(), nullable=True))
    op.add_column(
        "modal_invocations", sa.Column("output", sa.LargeBinary(), nullable=True)
    )
    op.drop_column("modal_invocations", "execution_time_seconds")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_invocations",
        sa.Column(
            "execution_time_seconds",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("modal_invocations", "output")
    op.drop_column("modal_invocations", "error")
    op.drop_column("modal_invocations", "status")
    op.drop_column("modal_invocations", "date_resolved")
    # ### end Alembic commands ###
