"""add example_usage field

Revision ID: adb2c9221c09
Revises: a20517924976
Create Date: 2025-02-05 20:36:56.258586

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adb2c9221c09"
down_revision: Union[str, None] = "a20517924976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_functions", sa.Column("example_usage", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_functions", "example_usage")
    # ### end Alembic commands ###
