"""use ids instead of DOIs

Revision ID: b56d8ac560a5
Revises: 8436147ae70a
Create Date: 2024-06-17 22:58:22.747543

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b56d8ac560a5"
down_revision: Union[str, None] = "8436147ae70a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gardens_entrypoints", sa.Column("garden_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "gardens_entrypoints", sa.Column("entrypoint_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "gardens_entrypoints_garden_doi_fkey", "gardens_entrypoints", type_="foreignkey"
    )
    op.drop_constraint(
        "gardens_entrypoints_entrypoint_doi_fkey",
        "gardens_entrypoints",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "gardens_entrypoints", "entrypoints", ["entrypoint_id"], ["id"]
    )
    op.create_foreign_key(None, "gardens_entrypoints", "gardens", ["garden_id"], ["id"])
    op.drop_column("gardens_entrypoints", "garden_doi")
    op.drop_column("gardens_entrypoints", "entrypoint_doi")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gardens_entrypoints",
        sa.Column("entrypoint_doi", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "gardens_entrypoints",
        sa.Column("garden_doi", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "gardens_entrypoints", type_="foreignkey")
    op.drop_constraint(None, "gardens_entrypoints", type_="foreignkey")
    op.create_foreign_key(
        "gardens_entrypoints_entrypoint_doi_fkey",
        "gardens_entrypoints",
        "entrypoints",
        ["entrypoint_doi"],
        ["doi"],
    )
    op.create_foreign_key(
        "gardens_entrypoints_garden_doi_fkey",
        "gardens_entrypoints",
        "gardens",
        ["garden_doi"],
        ["doi"],
    )
    op.drop_column("gardens_entrypoints", "entrypoint_id")
    op.drop_column("gardens_entrypoints", "garden_id")
    # ### end Alembic commands ###
