"""remove search index sync

Revision ID: c833519fb002
Revises: 84833e6b7062
Create Date: 2024-10-15 20:13:28.975222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c833519fb002"
down_revision: Union[str, None] = "84833e6b7062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("failed_search_index_updates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_search_index_updates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("doi", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("operation_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("retry_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_attempt", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="failed_search_index_updates_pkey"),
        sa.UniqueConstraint("doi", name="failed_search_index_updates_doi_key"),
    )
    # ### end Alembic commands ###
