"""Revise Modal app and function models to get basic POST and GET endpoints working

Revision ID: cc177f1d8341
Revises: 40c327013756
Create Date: 2024-10-03 21:14:17.700635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc177f1d8341'
down_revision: Union[str, None] = '40c327013756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modal_apps_modal_functions')
    op.add_column('modal_apps', sa.Column('base_image_name', sa.String(), nullable=False))
    op.add_column('modal_apps', sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('modal_apps', sa.Column('file_contents', sa.String(), nullable=False))
    op.drop_column('modal_apps', 'file_text')
    op.add_column('modal_functions', sa.Column('title', sa.String(), nullable=False))
    op.add_column('modal_functions', sa.Column('function_name', sa.String(), nullable=False))
    op.add_column('modal_functions', sa.Column('modal_app_id', sa.Integer(), nullable=False))
    op.alter_column('modal_functions', 'doi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('modal_functions_user_id_fkey', 'modal_functions', type_='foreignkey')
    op.create_foreign_key(None, 'modal_functions', 'modal_apps', ['modal_app_id'], ['id'])
    op.drop_column('modal_functions', 'contributors')
    op.drop_column('modal_functions', 'short_name')
    op.drop_column('modal_functions', 'language')
    op.drop_column('modal_functions', 'version')
    op.drop_column('modal_functions', 'user_id')
    op.drop_column('modal_functions', 'requirements')
    op.drop_column('modal_functions', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modal_functions', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('requirements', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('modal_functions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('modal_functions', sa.Column('contributors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modal_functions', type_='foreignkey')
    op.create_foreign_key('modal_functions_user_id_fkey', 'modal_functions', 'users', ['user_id'], ['id'])
    op.alter_column('modal_functions', 'doi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('modal_functions', 'modal_app_id')
    op.drop_column('modal_functions', 'function_name')
    op.drop_column('modal_functions', 'title')
    op.add_column('modal_apps', sa.Column('file_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('modal_apps', 'file_contents')
    op.drop_column('modal_apps', 'requirements')
    op.drop_column('modal_apps', 'base_image_name')
    op.create_table('modal_apps_modal_functions',
    sa.Column('modal_app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modal_function_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['modal_app_id'], ['modal_apps.id'], name='modal_apps_modal_functions_modal_app_id_fkey'),
    sa.ForeignKeyConstraint(['modal_function_id'], ['modal_functions.id'], name='modal_apps_modal_functions_modal_function_id_fkey'),
    sa.PrimaryKeyConstraint('modal_app_id', 'modal_function_id', name='modal_apps_modal_functions_pkey')
    )
    # ### end Alembic commands ###
