"""split invocations table

Revision ID: d37f6ea4ae3f
Revises: 892bac5ccc7c
Create Date: 2025-04-14 16:00:08.072750

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d37f6ea4ae3f"
down_revision: Union[str, None] = "892bac5ccc7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modal_invocation_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.Column(
            "date_invoked",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("date_resolved", sa.DateTime(), nullable=True),
        sa.Column("estimated_usage", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["modal_functions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modal_invocation_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("function_call_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "DONE",
                "ERROR",
                "TIMED_OUT",
                name="asyncmodaljobstatus",
                create_type=False,  # Use existing type
            ),
            nullable=False,
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("output", sa.LargeBinary(), nullable=True),
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["function_id"], ["modal_functions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["log_id"],
            ["modal_invocation_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # First migrate data to modal_invocation_logs
    op.execute("""
        INSERT INTO modal_invocation_logs (
            id, user_id, function_id,
            date_invoked, date_resolved, estimated_usage
        )
        SELECT
            id, user_id, function_id,
            date_invoked, date_resolved, estimated_usage
        FROM modal_invocations
    """)

    # Then migrate data to modal_invocation_results, ensuring log_id matches
    op.execute("""
        INSERT INTO modal_invocation_results (
            id, function_id, function_call_id, status,
            error, output, log_id
        )
        SELECT
            id, function_id, function_call_id, status,
            error, output, id
        FROM modal_invocations
        WHERE id IN (SELECT id FROM modal_invocation_logs)
    """)

    op.drop_table("modal_invocations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modal_invocations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("function_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "date_invoked",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "estimated_usage",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "function_call_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "date_resolved", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "ERROR",
                "DONE",
                "TIMED_OUT",
                name="asyncmodaljobstatus",
                create_type=False,  # Use existing type
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("output", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["modal_functions.id"],
            name="modal_invocations_function_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="modal_invocations_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="modal_invocations_pkey"),
    )

    # Migrate data back from both tables to modal_invocations
    op.execute("""
        INSERT INTO modal_invocations (
            id, user_id, function_id, function_call_id,
            date_invoked, date_resolved, estimated_usage,
            status, error, output
        )
        SELECT
            l.id, l.user_id, l.function_id, r.function_call_id,
            l.date_invoked, l.date_resolved, l.estimated_usage,
            r.status, r.error, r.output
        FROM modal_invocation_logs l
        LEFT JOIN modal_invocation_results r ON l.id = r.log_id
    """)

    op.drop_table("modal_invocation_results")
    op.drop_table("modal_invocation_logs")
    # ### end Alembic commands ###
