"""fix function_id ondelete for invocation logs

Revision ID: d5ae091961f1
Revises: d37f6ea4ae3f
Create Date: 2025-04-14 18:31:19.957927

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5ae091961f1"
down_revision: Union[str, None] = "d37f6ea4ae3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "modal_invocation_logs_function_id_fkey",
        "modal_invocation_logs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "modal_invocation_logs",
        "modal_functions",
        ["function_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "modal_invocation_logs", type_="foreignkey")
    op.create_foreign_key(
        "modal_invocation_logs_function_id_fkey",
        "modal_invocation_logs",
        "modal_functions",
        ["function_id"],
        ["id"],
    )
    # ### end Alembic commands ###
