"""add state column to gardens table

Revision ID: d73f1de91ed4
Revises: d5ae091961f1
Create Date: 2025-04-28 18:50:21.390134

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d73f1de91ed4"
down_revision: Union[str, None] = "d5ae091961f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    garden_state = postgresql.ENUM("DRAFT", "PUBLISHED", "ARCHIVED", name="gardenstate")
    garden_state.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gardens",
        sa.Column(
            "state",
            sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="gardenstate"),
            nullable=False,
            server_default="DRAFT",
        ),
    )

    # Set state for existing records based on is_archived and doi_is_draft
    connection = op.get_bind()
    connection.execute(
        sa.text("""
            UPDATE gardens
            SET state = CASE
                WHEN is_archived = true THEN 'ARCHIVED'::gardenstate
                WHEN doi_is_draft = true THEN 'DRAFT'::gardenstate
                ELSE 'PUBLISHED'::gardenstate
            END
        """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gardens", "state")
    op.execute("DROP TYPE IF EXISTS gardenstate")
    # ### end Alembic commands ###
