"""add original app name to modal apps

Revision ID: d999772cdd94
Revises: adb2c9221c09
Create Date: 2025-02-28 19:27:58.208627

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d999772cdd94"
down_revision: Union[str, None] = "adb2c9221c09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modal_apps", sa.Column("original_app_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_apps", "original_app_name")
    # ### end Alembic commands ###
