"""add marked_for_deletion to gardens and modal apps

Revision ID: e5b089c87930
Revises: 1db34d77bcf0
Create Date: 2025-04-30 14:28:26.631620

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5b089c87930"
down_revision: Union[str, None] = "1db34d77bcf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gardens", sa.Column("marked_for_deletion", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "modal_apps", sa.Column("marked_for_deletion", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("modal_apps", "marked_for_deletion")
    op.drop_column("gardens", "marked_for_deletion")
    # ### end Alembic commands ###
