"""add owner to hpc endpoints

Revision ID: ed08efa98b3b
Revises: 2700137da902
Create Date: 2025-11-04 20:40:21.054279

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed08efa98b3b"
down_revision: Union[str, None] = "2700137da902"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hpc_endpoints", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "hpc_endpoints", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hpc_endpoints", type_="foreignkey")
    op.drop_column("hpc_endpoints", "user_id")
    # ### end Alembic commands ###
