"""Add Modal models

Revision ID: ed639e44d5f1
Revises: 270b5e065306
Create Date: 2024-09-05 20:08:16.508038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed639e44d5f1"
down_revision: Union[str, None] = "270b5e065306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modal_apps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_name", sa.String(), nullable=False),
        sa.Column("file_text", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modal_functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(), nullable=False),
        sa.Column("doi_is_draft", sa.Boolean(), nullable=False),
        sa.Column("authors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("contributors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=False),
        sa.Column("year", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("function_text", sa.String(), nullable=False),
        sa.Column("test_functions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("requirements", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "models",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.Column(
            "repositories",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.Column(
            "papers",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.Column(
            "datasets",
            postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_table(
        "modal_apps_modal_functions",
        sa.Column("modal_app_id", sa.Integer(), nullable=False),
        sa.Column("modal_function_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["modal_app_id"],
            ["modal_apps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modal_function_id"],
            ["modal_functions.id"],
        ),
        sa.PrimaryKeyConstraint("modal_app_id", "modal_function_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("modal_apps_modal_functions")
    op.drop_table("modal_functions")
    op.drop_table("modal_apps")
    # ### end Alembic commands ###
