"""Get rid of secondary table

Revision ID: ede8c8249b38
Revises: 2f4ff0f6c36e
Create Date: 2024-10-02 21:58:09.339113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede8c8249b38'
down_revision: Union[str, None] = '2f4ff0f6c36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
