"""add fields to users table, create users_saved_gardens relationship to support saved gardens

Revision ID: f293268b31c5
Revises: 11833f8cea54
Create Date: 2024-07-03 18:52:08.873387

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f293268b31c5"
down_revision: Union[str, None] = "11833f8cea54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_saved_gardens",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("garden_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["garden_id"],
            ["gardens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "users", sa.Column("domains", postgresql.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "users", sa.Column("affiliations", postgresql.ARRAY(sa.String()), nullable=True)
    )
    op.add_column("users", sa.Column("profile_pic_id", sa.Integer()), nullable=True)
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "affiliations")
    op.drop_column("users", "domains")
    op.drop_column("users", "skills")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "email")
    op.drop_column("users", "name")
    op.drop_column("users", "profile_pic_id")
    op.drop_table("users_saved_gardens")
    # ### end Alembic commands ###
