"""create table for hpc functions

Revision ID: f8aea08d7d5d
Revises: 94dfc9916805
Create Date: 2025-09-29 20:17:29.387318

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f8aea08d7d5d"
down_revision: Union[str, None] = "94dfc9916805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hpc_deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deployment_type", sa.String(length=10), nullable=False),
        sa.Column("conda_env_name", sa.String(), nullable=True),
        sa.Column("conda_env_path", sa.String(), nullable=True),
        sa.Column(
            "conda_requirements", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("python_dependencies", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hpc_endpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("gcmu_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hpc_deployment_endpoints",
        sa.Column("hpc_deployment_id", sa.Integer(), nullable=False),
        sa.Column("hpc_endpoint_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hpc_deployment_id"],
            ["hpc_deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hpc_endpoint_id"],
            ["hpc_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("hpc_deployment_id", "hpc_endpoint_id"),
    )
    op.create_table(
        "hpc_functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("doi_is_draft", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("models", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("repositories", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("papers", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("datasets", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("notebooks", sa.ARRAY(sa.JSON()), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("authors", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("year", sa.String(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("function_name", sa.String(), nullable=False),
        sa.Column("function_text", sa.String(), nullable=False),
        sa.Column("example_usage", sa.String(), nullable=True),
        sa.Column("test_functions", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("requirements", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("conda_requirements", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["hpc_deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_table(
        "gardens_hpc_functions",
        sa.Column("garden_id", sa.Integer(), nullable=False),
        sa.Column("hpc_function_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["garden_id"],
            ["gardens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hpc_function_id"], ["hpc_functions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("garden_id", "hpc_function_id"),
    )
    op.create_table(
        "hpc_invocation_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("hpc_endpoint_id", sa.Integer(), nullable=False),
        sa.Column("globus_task_id", sa.String(), nullable=False),
        sa.Column("date_invoked", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["hpc_functions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hpc_endpoint_id"],
            ["hpc_endpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hpc_invocation_logs")
    op.drop_table("gardens_hpc_functions")
    op.drop_table("hpc_functions")
    op.drop_table("hpc_deployment_endpoints")
    op.drop_table("hpc_endpoints")
    op.drop_table("hpc_deployments")
    # ### end Alembic commands ###
