version: "3.0"

scanning-settings:
  max-depth: 6
  exclude: []
  include-files: []
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      vulnerabilities:
        67599: # Vulnerability ID
          reason: this is for an issue in pip 24.0 that only applies if installing from a private index. it's also apparently just the intended behavior.

        70612:
          reason: Jinja2 is only a dependency because of safety itself. Also, per the vulnerability description, the maintainer and multiple third parties believe that this vulnerability isn't valid.

        75976:
          reason: This only affects users that execute un-trusted templates. We don't do that here, so we can safely ignore this for now.

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - high
        - medium
      exploitability:
        - critical
        - high
        - medium

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

installation:
  default-action: allow
  audit-logging:
    enabled: true
  allow:
    packages: []
    vulnerabilities: {}
  deny:
    packages: {}
    vulnerabilities:
      warning-on-any-of:
        cvss-severity: []
      block-on-any-of:
        cvss-severity: []
