services:
  api:
    build:
      context: .
      args:
        INSTALL_DEV: true
    ports:
      - "5500:80"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
    entrypoint: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
    depends_on:
      dev-db:
        condition: service_healthy

  dev-db:
    hostname: dev-db
    image: postgres:16
    env_file:
      - .postgres.env
    volumes:
      - db-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -h localhost -d $${POSTGRES_DB} -p 5432"
      timeout: 5s
      interval: 5s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      # compose reads these from the default .env
      - PGADMIN_DEFAULT_EMAIL=${DB_USERNAME}@example.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgadmin-data:/root/.pgadmin
    ports:
      - "8080:80"
    depends_on:
      - dev-db

volumes:
  db-data-volume: # volume to persist database data between containers
  pgadmin-data:
