services:
  dev-api:
    build:
      context: .
      args:
        INSTALL_DEV: true
    ports:
      - "5500:80"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./.env:/app/.env
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
    entrypoint: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
    depends_on:
      dev-db:
        condition: service_healthy

  dev-db:
    hostname: dev-db
    image: postgres:16
    env_file:
      - .env.postgres
    volumes:
      - db-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -h localhost -d $${POSTGRES_DB} -p 5432"
      timeout: 5s
      interval: 5s

volumes:
  db-data-volume: # volume to persist database data between containers
