name: tests
on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.1

      - name: Install dependencies
        run: |
          cd ./garden-backend-service
          poetry install --no-interaction --no-ansi --with=develop

      - name: Test with pytest
        run: |
          cd ./garden-backend-service
          poetry run pytest

      - name: Check for vulnerable libraries with safety
        run: |
          cd ./garden-backend-service
          poetry run safety check
