name: tests
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: build
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::557062710055:role/GH_Actions_Garden_Secret_Reader
          role-session-name: garden-backend-tester
          aws-region: us-east-1

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install -r ./app/requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are any-flake8 comments
          flake8

      - name: Test with pytest
        run: |
          pytest ./app/test_app.py

      - name: Perform Type Checking With mypy
        run: |
          mypy .

      - name: Check for vulnerable libraries with safety
        run: |
          safety check
