name: Build and Push Docker Image to Lightsail

on:
  workflow_dispatch:
      inputs:
        version:
          description: 'Image version tag'
          required: true
          default: 'latest'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Determine the environment suffix to target to based on the branch
    - name: Set Environment
      id: vars
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
          echo "env=prod" >> $GITHUB_OUTPUT
        else
          echo "env=dev" >> $GITHUB_OUTPUT
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./garden-backend-service
        push: true
        tags: gardenai/garden-service:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::557062710055:role/GH-action-garden-backend-lightsail-deployer
        aws-region: us-east-1

    - name: Read lightsail deployment config
      id: read_config
      run: |
        CONFIG_JSON=$(cat ./infra/modules/lightsail/deployment-config.json | jq -c .)
        echo $CONFIG_JSON
        echo "config=$CONFIG_JSON" >> $GITHUB_OUTPUT

    - name:  Deploy new image to lightsail container service
      run: |
        aws lightsail create-container-service-deployment \
          --service-name garden-service-${{ steps.vars.outputs.env }} \
          --cli-input-json "${{ steps.read_config.outputs.config }}"
